version: '3.1'
services:
  mongo-container:
    # Match version in tests
    image: mongo:4.0.28
    container_name: mongo-forevely
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command: mongod
